
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Pre-check for any existing Supabase session keys in storage.
// If no session keys exist, disable autoRefreshToken to avoid refresh_token_not_found noise.
const hasSupabaseSession = (() => {
  try {
    // Look for common Supabase keys in localStorage/sessionStorage
    const lsKeys = Object.keys(localStorage || {});
    const ssKeys = Object.keys(sessionStorage || {});
    const allKeys = [...lsKeys, ...ssKeys];
    return allKeys.some((k) => k.startsWith('supabase.auth.') || k.includes('sb-'));
  } catch {
    return false;
  }
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: hasSupabaseSession,
  }
});
